### ISSUE TITLE
Shine fails to start Lustre 2.10.0 file system

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#526]
This is with OpenHPC 1.3 on EL7:
```
# shine -f testfs1 start
Traceback (most recent call last):
  File "/opt/ohpc/pub/libs/shine/1.5/sbin/shine", line 34, in <module>
    sys.exit(Controller().run_command())
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Controller.py", line 254, in run_command
    rc = command.filter_rc(command.execute())
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Commands/Base/FSLiveCommand.py", line 105, in execute
    result = max(result, self.execute_fs(fs, fs_conf, eh, vlevel))
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Commands/Start.py", line 95, in execute_fs
    tunings=Tune.get_tuning(fs_conf, fs.components))
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/FileSystem.py", line 529, in start
    actions.launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 218, in launch
    self._launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 272, in _launch
    if not self._graph_ok(self._members):
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 177, in _graph_ok
    dep.launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 218, in launch
    self._launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 272, in _launch
    if not self._graph_ok(self._members):
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 177, in _graph_ok
    dep.launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 218, in launch
    self._launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 272, in _launch
    if not self._graph_ok(self._members):
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 177, in _graph_ok
    dep.launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Action.py", line 218, in launch
    self._launch()
  File "/opt/ohpc/pub/libs/shine/1.5/lib/python2.7/site-packages/Shine/Lustre/Actions/Install.py", line 50, in _launch
    nodes=self.nodes, handler=self)
  File "/opt/ohpc/pub/libs/clustershell/1.7.3/lib/python2.7/site-packages/ClusterShell/Task.py", line 629, in copy
    reverse=reverse)
  File "/opt/ohpc/pub/libs/clustershell/1.7.3/lib/python2.7/site-packages/ClusterShell/Worker/Exec.py", line 290, in __init__
    self._create_clients(timeout=timeout, **kwargs)
  File "/opt/ohpc/pub/libs/clustershell/1.7.3/lib/python2.7/site-packages/ClusterShell/Worker/Exec.py", line 310, in _create_clients
    self._add_client(node, rank=rank, **kwargs)
  File "/opt/ohpc/pub/libs/clustershell/1.7.3/lib/python2.7/site-packages/ClusterShell/Worker/Exec.py", line 330, in _add_client
    raise ValueError("missing command or source parameter in "
ValueError: missing command or source parameter in worker constructor
```
[mylustre.lmf.txt](https://github.com/openhpc/ohpc/files/1233922/mylustre.lmf.txt)

**Comment by crbaird** [comment]
Hi @LaHaine. Thanks for pointing this out. The latest release of shine (v1.5) explicitly supports lustre up to 2.9. It would probably be worthwhile to open an issue on their [github](https://github.com/cea-hpc/shine) as well.

**Comment by LaHaine** [comment]
@crbaird : OK, done
https://github.com/cea-hpc/shine/issues/203
